// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

// User roles matching backend enum
export type UserRole =
  | 'Admin'
  | 'ClusterManager'
  | 'Supervisor'
  | 'AgronomyExpert'
  | 'UavVendor';

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  teamId: string;
  bio: string;
}>;

// Backend Result wrapper
export type Result<T> = {
  succeeded: boolean;
  data: T;
  message?: string;
  errors?: string[];
};

// Token data from login/refresh endpoints
export type TokenData = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string; // ISO date string
};

// Login response
export type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
  user: User;
};

// Legacy type for backward compatibility
export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

// Expert Approval Types
export type TaskStatus = 
  | 'PendingApproval'
  | 'Approved'
  | 'Rejected'
  | 'InProgress'
  | 'Completed'
  | 'Cancelled';

export type TaskPriority = 
  | 'Low'
  | 'Medium'
  | 'High'
  | 'Urgent';

export type ExpertPendingPlanItem = {
    id: string;
    planName: string;
    groupId: string;
    groupArea: string;
    basePlantingDate: string;
    status: TaskStatus;
    submittedAt: string | null;
    submitterName: string;
};

export type GetPendingApprovalsParams = {
  currentPage?: number;
  pageSize?: number;
  status?: TaskStatus;
  priority?: TaskPriority;
};

export type PagedResult<T> = {
  currentPage: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  hasPrevious: boolean;
  hasNext: boolean;
  succeeded: boolean;
  data: T;
  message?: string;
  errors?: string[];
};

export type ApproveRejectPlanInput = {
  planId: string;
  approved: boolean;
  notes?: string;
};

// Plan Detail types for expert plan details endpoint
export type PlanDetailMaterial = {
  materialId: string;
  materialName: string;
  materialUnit: string;
  quantityPerHa: number;
  estimatedAmount: number;
};

export type PlanDetailTask = {
  id: string;
  taskName: string;
  description: string | null;
  taskType: string;
  scheduledDate: string | null;
  scheduledEndDate: string | null;
  priority: TaskPriority | string;
  sequenceOrder: number;
  estimatedMaterialCost: number;
  materials: PlanDetailMaterial[];
};

export type PlanDetailStage = {
  id: string;
  stageName: string;
  sequenceOrder: number;
  typicalDurationDays: number;
  colorCode: string | null;
  tasks: PlanDetailTask[];
};

export type PlanDetailPlot = {
  id: string;
  area: number;
  soThua: string | null;
  soTo: string | null;
  soilType: string | null;
  status: string;
  farmerId: string;
};

export type PlanDetailGroup = {
  id: string;
  clusterName: string;
  totalArea: number;
  status: string;
  plots: PlanDetailPlot[];
};

export type PlanDetail = {
  id: string;
  planName: string;
  standardPlanId: string;
  groupId: string;
  totalArea: number;
  basePlantingDate: string;
  status: TaskStatus | string;
  estimatedTotalPlanCost: number;
  groupDetails: PlanDetailGroup;
  stages: PlanDetailStage[];
};
