// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

// User roles matching backend enum
export type UserRole =
  | 'Admin'
  | 'ClusterManager'
  | 'Supervisor'
  | 'AgronomyExpert'
  | 'UavVendor';

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  teamId: string;
  bio: string;
}>;

// Backend Result wrapper
export type Result<T> = {
  succeeded: boolean;
  data: T;
  message?: string;
  errors?: string[];
};

// Token data from login/refresh endpoints
export type TokenData = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string; // ISO date string
};

// Login response
export type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
  user: User;
};

// Legacy type for backward compatibility
export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;
